% Load data set
%load('21052018_transfer1.mat','myNet');
load('ultrasonografi_tabel.mat');
load('trainingAlexnet_nextLevel2.mat','myNet'); %%myNet adalah hasil dari alex net training
% Options for step 1.
optionsStage1 = trainingOptions('sgdm', ...
    'MaxEpochs', 20, ...
    'InitialLearnRate', 1e-5, ...
    'CheckpointPath', tempdir);

% Options for step 2.
optionsStage2 = trainingOptions('sgdm', ...
    'MaxEpochs', 20, ...
    'InitialLearnRate', 1e-5, ...
    'CheckpointPath', tempdir);

% Options for step 3.
optionsStage3 = trainingOptions('sgdm', ...
    'MaxEpochs', 20, ...
    'InitialLearnRate', 1e-6, ...
    'CheckpointPath', tempdir);

% Options for step 4.
optionsStage4 = trainingOptions('sgdm', ...
    'MaxEpochs', 20, ...
    'InitialLearnRate', 1e-6, ...
    'CheckpointPath', tempdir);

% % Options for step 5.
% optionsStage5 = trainingOptions('sgdm', ...
%     'MaxEpochs', 20, ...
%     'InitialLearnRate', 1e-7, ...
%     'CheckpointPath', tempdir);
% 
% % Options for step 6.
% optionsStage6 = trainingOptions('sgdm', ...
%     'MaxEpochs', 20, ...
%     'InitialLearnRate', 1e-7, ...
%     'CheckpointPath', tempdir);

options = [
    optionsStage1
    optionsStage2
    optionsStage3
    optionsStage4
%     optionsStage5
%     optionsStage6
    ];
% A trained network is loaded from disk to save time when running the
% example. Set this flag to true to train the network.

    % Train Faster R-CNN detector. Select a BoxPyramidScale of 1.2 to allow
    % for finer resolution for multiscale object detection.
    detector = trainFasterRCNNObjectDetector(ultrasonografi_tabel, myNet, options, ...
        'NegativeOverlapRange', [0 0.3], ...
        'PositiveOverlapRange', [0.5 1], ...
        'BoxPyramidScale', 1.2);
